name: Sync Multi - Branches to Multiple Platforms via SSH

on:
  push:
    branches:
      - '*'  # 监听所有分支的推送事件
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 进行完整克隆
          
      - name: Configure Git user
        run: |
          git config --global user.name '流体石头'
          git config --global user.email 'xueyao.me@gmail.com'

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote repositories
        run: |
          git remote add github git@github.com:tooleasy/tooleasy.github.io.git
          

      - name: Add host keys to known_hosts
        run: |
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        

          
      - name: Get current branch
        id: get_branch
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"

      - name: Push to targets
        run: |
          git push --force github ${{ steps.get_branch.outputs.branch }}
         
